use HANGKHONG;

CREATE TABLE FLIGHT (
    MaCB VARCHAR(50) PRIMARY KEY,
    GaDi VARCHAR(100),
    GaDen VARCHAR(100),
    DoDai INT,
    GioDi TIME,
    GioDen TIME,
    ChiPhi DECIMAL(10, 2)
);

CREATE TABLE MAYBAY (
    MaMB VARCHAR(50) PRIMARY KEY,
    Loai VARCHAR(100),
    TamBay INT
);

CREATE TABLE NHANVIEN (
    MaNV VARCHAR(50) PRIMARY KEY,
    Ten VARCHAR(100),
    Luong DECIMAL(10, 2)
);

CREATE TABLE CHUNGNHAN (
    MaNV VARCHAR(50),
    MaMB VARCHAR(50),
    PRIMARY KEY (MaNV, MaMB),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    FOREIGN KEY (MaMB) REFERENCES MAYBAY(MaMB)
);

